import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requireSession } from "@/lib/session";
import { db } from "@/db";
import { children, parentChildren, childCenters, centers, cases, followUps, caseServices, services, medicalReports, childProfiles, disabilities } from "@/db/schema";
import { and, eq, desc } from "drizzle-orm";
import { calculateAge, formatDate, statusLabels } from "@/lib/utils";
import { ArrowRight, Building2, CalendarCheck, FileText, HeartPulse, MapPin, Phone, ShieldCheck } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function ParentChildPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireSession();
  if (session.user.accountType !== "PARENT" || !session.user.parentId) redirect("/dashboard");
  const { id } = await params;
  const [owned] = await db.select({ child: children }).from(parentChildren).innerJoin(children, eq(parentChildren.childId, children.id)).where(and(eq(parentChildren.parentId, session.user.parentId), eq(parentChildren.childId, id))).limit(1);
  if (!owned) notFound();
  const [profileRows, memberships, caseRows] = await Promise.all([
    db.select({ profile: childProfiles, disabilityName: disabilities.name }).from(childProfiles).leftJoin(disabilities, eq(childProfiles.disabilityId, disabilities.id)).where(eq(childProfiles.childId, id)).limit(1),
    db.select({ membership: childCenters, center: centers }).from(childCenters).innerJoin(centers, eq(childCenters.centerId, centers.id)).where(eq(childCenters.childId, id)).orderBy(desc(childCenters.joinedAt)),
    db.select({ id: cases.id, caseNumber: cases.caseNumber, centerId: cases.centerId, status: cases.status, registrationDate: cases.registrationDate, centerName: centers.name }).from(cases).innerJoin(centers, eq(cases.centerId, centers.id)).where(eq(cases.childId, id)).orderBy(desc(cases.updatedAt)),
  ]);
  const [followups, serviceRows, reports] = caseRows.length ? await Promise.all([
    db.select({ id: followUps.id, followUpDate: followUps.followUpDate, progress: followUps.progress, observations: followUps.observations, recommendations: followUps.recommendations, centerName: centers.name }).from(followUps).innerJoin(cases, eq(followUps.caseId, cases.id)).innerJoin(centers, eq(cases.centerId, centers.id)).where(eq(cases.childId, id)).orderBy(desc(followUps.followUpDate)).limit(40),
    db.select({ id: caseServices.id, startDate: caseServices.startDate, endDate: caseServices.endDate, serviceName: services.name, centerName: centers.name }).from(caseServices).innerJoin(cases, eq(caseServices.caseId, cases.id)).innerJoin(services, eq(caseServices.serviceId, services.id)).innerJoin(centers, eq(cases.centerId, centers.id)).where(eq(cases.childId, id)).orderBy(desc(caseServices.startDate)).limit(40),
    db.select({ id: medicalReports.id, reportDate: medicalReports.reportDate, title: medicalReports.reportType, centerName: centers.name }).from(medicalReports).innerJoin(cases, eq(medicalReports.caseId, cases.id)).innerJoin(centers, eq(cases.centerId, centers.id)).where(eq(cases.childId, id)).orderBy(desc(medicalReports.reportDate)).limit(40),
  ]) : [[], [], []];
  const child = owned.child, profile = profileRows[0], age = calculateAge(child.dateOfBirth);
  return <div className="space-y-6">
    <Link href="/parent" className="inline-flex items-center gap-1 text-xs text-muted hover:text-primary"><ArrowRight className="h-3 w-3"/> العودة لأطفالي</Link>
    <section className="rounded-3xl border border-primary/10 bg-surface overflow-hidden shadow-sm"><div className="h-2 bg-gradient-to-l from-primary via-primary-light to-accent"/><div className="p-6"><div className="flex flex-col lg:flex-row lg:justify-between gap-5"><div className="flex items-start gap-4"><div className="h-16 w-16 rounded-2xl bg-primary/10 text-primary flex items-center justify-center text-2xl font-bold">{child.firstName.slice(0,1)}</div><div><p className="text-xs font-semibold text-primary">ملف الطفل</p><h1 className="text-2xl font-bold text-ink mt-1">{child.firstName} {child.middleName ?? ""} {child.lastName}</h1><p className="text-sm text-muted mt-1">{age} سنة · {child.gender === "MALE" ? "ذكر" : "أنثى"}{child.city ? ` · ${child.city}` : ""}</p></div></div><Link href="/centers" className="inline-flex h-10 items-center justify-center rounded-xl bg-primary px-4 text-sm font-semibold text-white">إضافة مركز للطفل</Link></div><div className="grid sm:grid-cols-3 gap-3 mt-6"><Metric icon={<HeartPulse className="h-4 w-4"/>} label="التشخيص العام" value={profile?.profile.diagnosisName ?? "غير مضاف"}/><Metric icon={<ShieldCheck className="h-4 w-4"/>} label="نوع الإعاقة" value={profile?.disabilityName ?? "غير مضاف"}/><Metric icon={<Building2 className="h-4 w-4"/>} label="المراكز" value={String(memberships.filter(m => m.membership.status === "ACTIVE").length)}/></div></div></section>
    <Section title="المراكز المرتبط بها الطفل" hint="كل مركز يحتفظ بمتابعته وخدماته الخاصة."><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{memberships.length ? memberships.map(({membership,center}) => <div key={membership.id} className="rounded-2xl border border-border bg-background p-4"><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center"><Building2 className="h-5 w-5"/></div><div className="flex-1"><p className="font-semibold">{center.name}</p><p className="text-xs text-muted mt-1">انضم {formatDate(membership.joinedAt)}</p></div><span className="text-[11px] rounded-full bg-success/10 text-success px-2.5 py-1">{membership.status === "ACTIVE" ? "نشط" : statusLabels[membership.status] ?? membership.status}</span></div>{center.address ? <p className="text-xs text-muted mt-4 flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{center.address}</p> : null}{center.phone ? <a href={`tel:${center.phone}`} className="text-xs text-primary mt-2 inline-flex items-center gap-1"><Phone className="h-3.5 w-3.5"/>{center.phone}</a> : null}</div>) : <Empty text="لم يتم ربط الطفل بأي مركز بعد."/>}</div></Section>
    <Section title="تطور الحالة عبر المراكز" hint="المتابعات التي سجلتها المراكز لهذا الطفل."><div className="space-y-3">{followups.length ? followups.map(f => <div key={f.id} className="rounded-2xl border border-border p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold text-sm">{f.centerName}</p><p className="text-xs text-muted mt-1">{formatDate(f.followUpDate)} · {statusLabels[f.progress] ?? f.progress}</p></div><CalendarCheck className="h-4 w-4 text-primary"/></div>{f.observations ? <p className="text-sm mt-3 leading-6"><b>الملاحظات:</b> {f.observations}</p> : null}{f.recommendations ? <p className="text-sm text-muted mt-2 leading-6"><b className="text-ink">التوصيات:</b> {f.recommendations}</p> : null}</div>) : <Empty text="لا توجد متابعات مسجلة حتى الآن."/>}</div></Section>
    <div className="grid lg:grid-cols-2 gap-5"><Section title="الخدمات والجلسات"><div className="space-y-3">{serviceRows.length ? serviceRows.map(s => <div key={s.id} className="rounded-xl bg-background p-4"><div className="flex justify-between gap-3"><p className="font-semibold text-sm">{s.serviceName}</p><span className="text-xs text-muted">{s.centerName}</span></div><p className="text-xs text-muted mt-1">{formatDate(s.startDate)}{s.endDate ? ` → ${formatDate(s.endDate)}` : " · مستمرة"}</p></div>) : <Empty text="لا توجد خدمات مسجلة."/>}</div></Section><Section title="التقارير"><div className="space-y-3">{reports.length ? reports.map(r => <div key={r.id} className="rounded-xl bg-background p-4"><div className="flex justify-between gap-3"><p className="font-semibold text-sm">{r.title ?? "تقرير طبي"}</p><span className="text-xs text-muted">{r.centerName}</span></div><p className="text-xs text-muted mt-1">{formatDate(r.reportDate)}</p></div>) : <Empty text="لا توجد تقارير مسجلة."/>}</div></Section></div>
  </div>;
}
function Section({title,hint,children}:{title:string;hint?:string;children:React.ReactNode}){return <section className="rounded-2xl border border-border bg-surface p-6"><h2 className="font-bold text-lg">{title}</h2>{hint ? <p className="text-xs text-muted mt-1 mb-5">{hint}</p> : <div className="mt-5"/>}{children}</section>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl bg-background p-4"><div className="flex items-center gap-2 text-primary">{icon}<span className="text-xs text-muted">{label}</span></div><p className="font-semibold text-sm mt-2">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="text-sm text-muted text-center py-8">{text}</p>}
