import type { ReactNode } from "react";
import Link from "next/link";
import { type AppSession, type AppRole } from "@/lib/auth";
import { requireSession } from "@/lib/session";
import { LayoutDashboard, ClipboardList, CalendarCheck, BarChart3, UserCog, Settings, Bell, Search, ShieldCheck, ScrollText, Building2, UserPlus } from "lucide-react";
import { AppSidebarClient, LogoutButton } from "./app-shell-client";
import { BrandLockup } from "./brand-mark";
interface NavItem{href:string;label:string;icon:React.ComponentType<{className?:string}>;roles?:AppRole[]}
const NAV:NavItem[]=[{href:"/dashboard",label:"لوحة التحكم",icon:LayoutDashboard},{href:"/cases",label:"الحالات",icon:ClipboardList},{href:"/intake",label:"انضمامات الأطفال",icon:UserPlus},{href:"/follow-ups",label:"المتابعات",icon:CalendarCheck},{href:"/reports",label:"التقارير",icon:BarChart3,roles:["SUPER_ADMIN","CENTER_ADMIN","SPECIALIST","VIEWER"]},{href:"/users",label:"المستخدمون",icon:UserCog,roles:["SUPER_ADMIN","CENTER_ADMIN"]},{href:"/audit",label:"سجل النشاط",icon:ScrollText,roles:["SUPER_ADMIN","CENTER_ADMIN"]},{href:"/settings",label:"الإعدادات",icon:Settings},{href:"/admin/platform",label:"نظرة عامة على المنصة",icon:LayoutDashboard,roles:["SUPER_ADMIN"]},{href:"/admin/centers",label:"إدارة المراكز",icon:Building2,roles:["SUPER_ADMIN"]}];
const PARENT_NAV:NavItem[]=[{href:"/parent",label:"أطفالي",icon:LayoutDashboard,roles:["PARENT"]},{href:"/centers",label:"المراكز",icon:Building2,roles:["PARENT"]}];
export async function AppShell({children}:{children:ReactNode}){const session=await requireSession();const user=session.user;const visibleNav=user.role==="PARENT"?PARENT_NAV:NAV.filter(n=>!n.roles||n.roles.includes(user.role));return <div className="flex min-h-screen bg-background"><a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:z-[100] focus:top-3 focus:start-3 focus:rounded-lg focus:bg-surface focus:px-4 focus:py-2 focus:text-sm focus:shadow-lg">تخطي إلى المحتوى</a><aside className="hidden lg:flex lg:w-64 lg:flex-col lg:fixed lg:inset-y-0 lg:start-0 border-e border-border bg-surface z-20"><SidebarBrand/><nav className="flex-1 px-3 py-4 space-y-1 overflow-y-auto">{visibleNav.map(item=><SidebarLink key={item.href} item={item}/>)}</nav><UserBlock user={user}/></aside><AppSidebarClient nav={visibleNav} user={user}><div className="lg:pe-0 lg:ps-64 flex-1 flex flex-col min-w-0"><TopBar user={user}/><main id="main-content" tabIndex={-1} className="flex-1 px-4 sm:px-6 lg:px-8 py-6 lg:py-8 min-w-0">{children}</main></div></AppSidebarClient></div>}
function SidebarBrand(){return <div className="h-20 flex items-center px-5 border-b border-border"><BrandLockup/></div>}
function SidebarLink({item}:{item:NavItem}){return <Link href={item.href} className="desktop-nav-link flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-muted hover:text-ink hover:bg-background transition-colors"><item.icon className="h-4 w-4"/><span className="flex-1">{item.label}</span></Link>}
const roleLabels:Record<AppRole,string>={SUPER_ADMIN:"مدير عام",CENTER_ADMIN:"مدير مركز",SPECIALIST:"أخصائي",DATA_ENTRY:"إدخال بيانات",VIEWER:"مشاهد"};
function UserBlock({user}:{user:AppSession["user"]}){return <div className="border-t border-border p-4"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-full bg-primary/10 text-primary flex items-center justify-center font-semibold text-sm">{user.name.slice(0,1)}</div><div className="flex-1 min-w-0"><p className="text-sm font-medium text-ink truncate">{user.name}</p><p className="text-xs text-muted truncate">{roleLabels[user.role]}</p></div><LogoutButton compact/></div></div>}
function TopBar({user}:{user:AppSession["user"]}){const isParent=user.role==="PARENT";const contextLabel=isParent?"بوابة ولي الأمر":user.role==="SUPER_ADMIN"?"إدارة المنصة":user.centerName||"مساحة المركز";return <div className="h-16 lg:h-auto lg:pt-0 border-b border-border bg-surface lg:bg-transparent lg:border-0 flex items-center justify-between px-4 lg:px-0 gap-3"><div className="flex items-center gap-2 lg:hidden ms-auto"><BrandLockup compact/></div><div className="hidden lg:flex items-center gap-3"><div className="rounded-full border border-success/20 bg-success/10 px-3 py-1.5 text-xs font-medium text-success"><span className="inline-flex items-center gap-1.5"><ShieldCheck className="h-3.5 w-3.5"/>{contextLabel}</span></div></div><div className="flex items-center gap-2 lg:hidden ms-auto">{!isParent?<><Link href="/cases" className="h-9 w-9 rounded-lg flex items-center justify-center text-muted hover:bg-background" aria-label="بحث"><Search className="h-4 w-4"/></Link><Link href="/settings" className="h-9 w-9 rounded-lg flex items-center justify-center text-muted hover:bg-background" aria-label="الإعدادات"><Bell className="h-4 w-4"/></Link></>:<Link href="/centers" className="h-9 rounded-lg px-3 flex items-center justify-center text-xs font-semibold text-primary bg-primary/10 hover:bg-primary/15">استكشف المراكز</Link>}</div></div>}
