import type { ReactNode } from "react";
import Link from "next/link";
import { ShieldCheck, Sparkles } from "lucide-react";
import { BrandLockup } from "@/components/brand-mark";
export default function PublicLayout({children}:{children:ReactNode}){return <div className="flex min-h-screen flex-col bg-background"><PublicNavbar/><main className="flex-1">{children}</main><PublicFooter/></div>}
function PublicNavbar(){return <header className="sticky top-0 z-30 border-b border-border bg-surface/80 backdrop-blur"><nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6"><Link href="/" className="flex items-center gap-2"><BrandLockup/></Link><div className="hidden lg:flex items-center gap-1"><NavLink href="/">الرئيسية</NavLink><NavLink href="/about">عن المنصة</NavLink><NavLink href="/features">المميزات</NavLink><NavLink href="/how-it-works">كيف تعمل؟</NavLink><NavLink href="/security">الأمان</NavLink></div><div className="flex items-center gap-2"><Link href="/login" className="hidden sm:inline-flex text-sm font-medium text-ink hover:text-primary px-3 py-2">تسجيل الدخول</Link><Link href="/login" className="inline-flex h-8 items-center gap-2 rounded-md bg-primary px-3 text-xs font-medium text-white hover:bg-primary/90 shadow-sm">ابدأ الآن</Link></div></nav></header>}
function NavLink({href,children}:{href:string;children:ReactNode}){return <Link href={href} className="text-sm font-medium text-ink hover:text-primary px-3 py-2 rounded-lg hover:bg-background transition-colors">{children}</Link>}
function PublicFooter(){return <footer className="border-t border-border bg-surface mt-20"><div className="mx-auto max-w-7xl px-6 py-12 grid grid-cols-2 md:grid-cols-4 gap-8"><div className="col-span-2"><BrandLockup/><p className="text-sm text-muted mt-4 max-w-md leading-relaxed">منصة متكاملة تساعد مراكز الرعاية على تنظيم بيانات الحالات، متابعة تطورها، وإدارة التقارير والإحصائيات من مكان واحد.</p><div className="flex items-center gap-2 mt-4 text-xs text-muted"><ShieldCheck className="h-4 w-4 text-success"/>تصميم يضع الخصوصية والتحكم في الوصول في المقدمة</div></div><div><p className="text-sm font-semibold text-ink mb-3">المنصة</p><ul className="space-y-2 text-sm text-muted"><li><Link href="/features" className="hover:text-primary">المميزات</Link></li><li><Link href="/how-it-works" className="hover:text-primary">كيف تعمل؟</Link></li><li><Link href="/security" className="hover:text-primary">الأمان</Link></li></ul></div><div><p className="text-sm font-semibold text-ink mb-3">الحساب</p><ul className="space-y-2 text-sm text-muted"><li><Link href="/login" className="hover:text-primary">تسجيل الدخول</Link></li><li><Link href="/dashboard" className="hover:text-primary">لوحة التحكم</Link></li></ul></div></div><div className="border-t border-border py-4 text-center text-xs text-muted">© {new Date().getFullYear()} Special Care — جميع الحقوق محفوظة.</div></footer>}
export function FeatureBlock({icon:Icon,title,description}:{icon:React.ComponentType<{className?:string}>;title:string;description:string}){return <div className="rounded-2xl border border-border bg-surface p-6 hover:border-primary-light transition-colors"><div className="h-11 w-11 rounded-xl bg-primary/10 text-primary flex items-center justify-center mb-4"><Icon className="h-5 w-5"/></div><h3 className="text-base font-semibold text-ink mb-1.5">{title}</h3><p className="text-sm text-muted leading-relaxed">{description}</p></div>}
export {Sparkles};
