"use client";
import * as React from "react";
import { useFormStatus } from "react-dom";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";
import { Loader2, Search, AlertCircle, CheckCircle2, Info, AlertTriangle, UploadCloud, X, File } from "lucide-react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import * as SelectPrimitive from "@radix-ui/react-select";
import * as AlertDialogPrimitive from "@radix-ui/react-alert-dialog";
import * as LabelPrimitive from "@radix-ui/react-label";
const buttonVariants=cva("inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-sm font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-light disabled:pointer-events-none disabled:opacity-50",{variants:{variant:{primary:"bg-primary text-white hover:bg-primary/90",secondary:"bg-surface border border-border text-ink hover:bg-background",outline:"border border-border bg-transparent text-ink hover:bg-background",ghost:"text-ink hover:bg-background",accent:"bg-accent text-white",danger:"bg-danger text-white",success:"bg-success text-white",link:"text-primary underline-offset-4 hover:underline"},size:{sm:"h-8 px-3 text-xs rounded-md",md:"h-10 px-4",lg:"h-12 px-6 text-base",icon:"h-10 w-10"}},defaultVariants:{variant:"primary",size:"md"}});
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement>,VariantProps<typeof buttonVariants>{loading?:boolean}
export const Button=React.forwardRef<HTMLButtonElement,ButtonProps>(({className,variant,size,loading,children,disabled,...props},ref)=><button ref={ref} className={cn(buttonVariants({variant,size,className}))} disabled={disabled||loading} {...props}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:null}{children}</button>);Button.displayName="Button";
export function SubmitButton({children,loadingText="جاري الحفظ...",className,variant="primary",size="md"}:{children:React.ReactNode;loadingText?:React.ReactNode;className?:string;variant?:VariantProps<typeof buttonVariants>["variant"];size?:VariantProps<typeof buttonVariants>["size"]}){const {pending}=useFormStatus();return <Button type="submit" variant={variant} size={size} className={className} loading={pending}>{pending?loadingText:children}</Button>}
export function Card({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("rounded-2xl border border-border bg-surface shadow-sm",className)} {...props}/>}
export function CardHeader({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("p-6",className)} {...props}/>}
export function CardTitle({className,...props}:React.HTMLAttributes<HTMLHeadingElement>){return <h3 className={cn("text-lg font-semibold text-ink",className)} {...props}/>}
export function CardDescription({className,...props}:React.HTMLAttributes<HTMLParagraphElement>){return <p className={cn("text-sm text-muted mt-1",className)} {...props}/>}
export function CardContent({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("p-6 pt-0",className)} {...props}/>}
export function CardFooter({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("p-6 pt-0 flex items-center gap-2",className)} {...props}/>}
const badgeVariants=cva("inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium",{variants:{variant:{default:"bg-primary/10 text-primary",success:"bg-success/10 text-success",danger:"bg-danger/10 text-danger",warning:"bg-warning/10 text-warning",muted:"bg-muted/10 text-muted",outline:"border border-border text-ink"}},defaultVariants:{variant:"default"}});
export function Badge({className,variant,...props}:React.HTMLAttributes<HTMLSpanElement>&VariantProps<typeof badgeVariants>){return <span className={cn(badgeVariants({variant}),className)} {...props}/>}
export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement>{icon?:React.ReactNode}
export const Input=React.forwardRef<HTMLInputElement,InputProps>(({className,icon,...props},ref)=><div className="relative">{icon?<span className="absolute inset-y-0 end-0 flex items-center pe-3 text-muted pointer-events-none">{icon}</span>:null}<input ref={ref} className={cn("flex h-10 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-ink placeholder:text-muted focus:outline-none focus:border-primary-light focus:ring-2 focus:ring-primary-light/20 disabled:opacity-50",icon&&"pe-10",className)} {...props}/></div>);Input.displayName="Input";
export const Textarea=React.forwardRef<HTMLTextAreaElement,React.TextareaHTMLAttributes<HTMLTextAreaElement>>(({className,...props},ref)=><textarea ref={ref} className={cn("flex min-h-[96px] w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-ink resize-y focus:outline-none focus:border-primary-light",className)} {...props}/>);Textarea.displayName="Textarea";
export const Label=React.forwardRef<React.ElementRef<typeof LabelPrimitive.Root>,React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root>>(({className,...props},ref)=><LabelPrimitive.Root ref={ref} className={cn("text-sm font-medium leading-none text-ink",className)} {...props}/>);Label.displayName="Label";
export function FormField({label,required,error,hint,children,className}:{label?:string;required?:boolean;error?:string;hint?:string;children:React.ReactNode;className?:string}){return <div className={cn("space-y-1.5",className)}>{label?<Label className="flex items-center gap-1">{label}{required?<span className="text-danger">*</span>:null}</Label>:null}{children}{hint&&!error?<p className="text-xs text-muted">{hint}</p>:null}{error?<p className="text-xs text-danger flex items-center gap-1"><AlertCircle className="h-3 w-3"/>{error}</p>:null}</div>}
export const Select=SelectPrimitive.Root;export const SelectGroup=SelectPrimitive.Group;export const SelectValue=SelectPrimitive.Value;
export const SelectTrigger=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Trigger>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>>(({className,children,...props},ref)=><SelectPrimitive.Trigger ref={ref} className={cn("flex h-10 w-full items-center justify-between rounded-lg border border-border bg-surface px-3 py-2 text-sm text-ink",className)} {...props}>{children}<SelectPrimitive.Icon>⌄</SelectPrimitive.Icon></SelectPrimitive.Trigger>);SelectTrigger.displayName="SelectTrigger";
export const SelectContent=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Content>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>>(({className,children,...props},ref)=><SelectPrimitive.Portal><SelectPrimitive.Content ref={ref} className={cn("z-50 min-w-[8rem] overflow-hidden rounded-lg border border-border bg-surface p-1 shadow-lg",className)} {...props}><SelectPrimitive.Viewport>{children}</SelectPrimitive.Viewport></SelectPrimitive.Content></SelectPrimitive.Portal>);SelectContent.displayName="SelectContent";
export const SelectItem=React.forwardRef<React.ElementRef<typeof SelectPrimitive.Item>,React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>>(({className,children,...props},ref)=><SelectPrimitive.Item ref={ref} className={cn("relative flex w-full cursor-default select-none items-center rounded-md px-3 py-2 text-sm outline-none data-[highlighted]:bg-background",className)} {...props}><SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText></SelectPrimitive.Item>);SelectItem.displayName="SelectItem";
export const Dialog=DialogPrimitive.Root;export const DialogTrigger=DialogPrimitive.Trigger;export const DialogClose=DialogPrimitive.Close;
export const DialogContent=React.forwardRef<React.ElementRef<typeof DialogPrimitive.Content>,React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>>(({className,children,...props},ref)=><DialogPrimitive.Portal><DialogPrimitive.Overlay className="fixed inset-0 z-50 bg-ink/40"/><DialogPrimitive.Content ref={ref} className={cn("fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-border bg-surface p-6 shadow-xl",className)} {...props}>{children}</DialogPrimitive.Content></DialogPrimitive.Portal>);DialogContent.displayName="DialogContent";
export function DialogHeader({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("flex flex-col gap-1.5",className)} {...props}/>};export function DialogTitle({className,...props}:React.ComponentPropsWithoutRef<typeof DialogPrimitive.Title>){return <DialogPrimitive.Title className={cn("text-lg font-semibold text-ink",className)} {...props}/>};export function DialogDescription({className,...props}:React.ComponentPropsWithoutRef<typeof DialogPrimitive.Description>){return <DialogPrimitive.Description className={cn("text-sm text-muted",className)} {...props}/>};export function DialogFooter({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("flex flex-col-reverse sm:flex-row sm:justify-end gap-2 pt-4",className)} {...props}/>}
export const AlertDialog=AlertDialogPrimitive.Root;export const AlertDialogTrigger=AlertDialogPrimitive.Trigger;export const AlertDialogContent=React.forwardRef<React.ElementRef<typeof AlertDialogPrimitive.Content>,React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Content>>(({className,children,...props},ref)=><AlertDialogPrimitive.Portal><AlertDialogPrimitive.Overlay className="fixed inset-0 z-50 bg-ink/40"/><AlertDialogPrimitive.Content ref={ref} className={cn("fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-border bg-surface p-6 shadow-xl",className)} {...props}>{children}</AlertDialogPrimitive.Content></AlertDialogPrimitive.Portal>);AlertDialogContent.displayName="AlertDialogContent";export const AlertDialogTitle=AlertDialogPrimitive.Title;export const AlertDialogDescription=AlertDialogPrimitive.Description;export const AlertDialogCancel=AlertDialogPrimitive.Cancel;export const AlertDialogAction=AlertDialogPrimitive.Action;export function AlertDialogFooter({className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn("flex flex-col-reverse sm:flex-row sm:justify-end gap-2 pt-4",className)} {...props}/>}
export function EmptyState({icon:Icon,title,description,action}:{icon?:React.ComponentType<{className?:string}>;title:string;description?:string;action?:React.ReactNode}){return <div className="flex flex-col items-center justify-center py-16 px-6 text-center">{Icon?<Icon className="h-10 w-10 text-muted mb-3"/>:null}<h3 className="text-base font-semibold text-ink">{title}</h3>{description?<p className="text-sm text-muted mt-1 max-w-md">{description}</p>:null}{action?<div className="mt-6">{action}</div>:null}</div>}
export function LoadingState({label="جاري التحميل..."}:{label?:string}){return <div className="flex flex-col items-center justify-center py-24 text-center"><Loader2 className="h-6 w-6 animate-spin text-primary"/><p className="text-sm text-muted mt-3">{label}</p></div>}
export function ErrorState({title="حدث خطأ",message="تعذّر تحميل البيانات. يرجى المحاولة لاحقًا."}:{title?:string;message?:string;onRetry?:()=>void}){return <div className="flex flex-col items-center justify-center py-16 text-center"><h3 className="text-base font-semibold text-ink">{title}</h3><p className="text-sm text-muted mt-1 max-w-md">{message}</p></div>}
export function Alert({variant="info",title,children}:{variant?:"info"|"success"|"warning"|"error";title?:string;children?:React.ReactNode}){const c={info:{bg:"bg-primary/10",color:"text-primary",Icon:Info},success:{bg:"bg-success/10",color:"text-success",Icon:CheckCircle2},warning:{bg:"bg-warning/10",color:"text-warning",Icon:AlertTriangle},error:{bg:"bg-danger/10",color:"text-danger",Icon:AlertCircle}}[variant];const Icon=c.Icon;return <div className={cn("flex gap-3 rounded-xl p-4",c.bg,c.color)}><Icon className="h-5 w-5"/><div>{title?<p className="font-semibold text-sm">{title}</p>:null}{children?<div className="text-sm mt-0.5">{children}</div>:null}</div></div>}
export function StatCard({title,value,hint,icon:Icon,tone="primary"}:{title:string;value:string|number;hint?:string;icon?:React.ComponentType<{className?:string}>;tone?:"primary"|"success"|"warning"|"accent"}){const tones={primary:"bg-primary/10 text-primary",success:"bg-success/10 text-success",warning:"bg-warning/10 text-warning",accent:"bg-accent/10 text-accent"};return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-muted">{title}</p><p className="text-2xl font-bold text-ink mt-2">{value}</p>{hint?<p className="text-xs text-muted mt-1">{hint}</p>:null}</div>{Icon?<div className={cn("h-10 w-10 rounded-xl flex items-center justify-center",tones[tone])}><Icon className="h-5 w-5"/></div>:null}</div></Card>}
export function PageHeader({title,subtitle,actions}:{title:string;subtitle?:string;actions?:React.ReactNode}){return <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-6"><div><h1 className="text-2xl font-bold text-ink">{title}</h1>{subtitle?<p className="text-sm text-muted mt-1">{subtitle}</p>:null}</div>{actions?<div className="flex items-center gap-2">{actions}</div>:null}</div>}
export function SearchInput({value,onChange,placeholder="بحث..."}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <Input icon={<Search className="h-4 w-4"/>} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}
export interface FileUploaderProps { value?: File | File[] | null; onChange?: (files: File | File[] | null) => void; onFilesChange?: (files: File[]) => void; multiple?: boolean; accept?: string; maxSize?: number; disabled?: boolean; className?: string; label?: React.ReactNode; description?: React.ReactNode; [key: string]: unknown; }
export function FileUploader({ value,onChange,onFilesChange,multiple=false,accept,maxSize,disabled=false,className,label="اختر ملفًا",description="اسحب الملف هنا أو اضغط للاختيار",...rest }: FileUploaderProps) {
  const inputRef=React.useRef<HTMLInputElement>(null); const [files,setFiles]=React.useState<File[]>(()=>Array.isArray(value)?value:value?[value]:[]); const [error,setError]=React.useState<string|null>(null);
  React.useEffect(()=>{if(Array.isArray(value))setFiles(value);else if(value)setFiles([value]);else if(value===null)setFiles([])},[value]);
  const handleFiles=(selected:File[])=>{setError(null);const filtered=maxSize?selected.filter(file=>{if(file.size>maxSize){setError(`حجم الملف ${file.name} أكبر من الحد المسموح`);return false}return true}):selected;const next=multiple?filtered:filtered.slice(0,1);setFiles(next);if(multiple)onFilesChange?.(next);onChange?.(multiple?next:(next[0]??null))};
  const removeFile=(index:number)=>{const next=files.filter((_,i)=>i!==index);setFiles(next);if(multiple)onFilesChange?.(next);onChange?.(multiple?next:(next[0]??null))};
  return <div className={cn("space-y-2",className)} {...(rest as React.HTMLAttributes<HTMLDivElement>)}><input ref={inputRef} type="file" className="sr-only" accept={accept} multiple={multiple} disabled={disabled} onChange={e=>handleFiles(Array.from(e.target.files??[]))}/><button type="button" disabled={disabled} onClick={()=>inputRef.current?.click()} className="w-full rounded-xl border-2 border-dashed border-border bg-background/50 p-6 text-center transition hover:border-primary-light hover:bg-background disabled:cursor-not-allowed disabled:opacity-50"><UploadCloud className="mx-auto h-8 w-8 text-muted"/><p className="mt-2 text-sm font-medium text-ink">{label}</p><p className="mt-1 text-xs text-muted">{description}</p></button>{error?<p className="text-xs text-danger">{error}</p>:null}{files.length?<div className="space-y-2">{files.map((file,index)=><div key={`${file.name}-${file.lastModified}-${index}`} className="flex items-center justify-between rounded-lg border border-border bg-surface px-3 py-2"><div className="flex min-w-0 items-center gap-2"><File className="h-4 w-4 shrink-0 text-muted"/><span className="truncate text-sm text-ink">{file.name}</span></div><button type="button" className="text-muted hover:text-danger" onClick={()=>removeFile(index)} aria-label="حذف الملف"><X className="h-4 w-4"/></button></div>)}</div>:null}</div>;
}

export function Tabs({defaultValue,children,className}:{defaultValue?:string;children:React.ReactNode;className?:string}){const [value,setValue]=React.useState(defaultValue??"");return <div className={cn("w-full",className)}>{React.Children.map(children,(child:any)=>React.isValidElement(child)?React.cloneElement(child,{value,setValue}):child)}</div>}
export function TabsList({children,className,value,setValue}:{children:React.ReactNode;className?:string;value?:string;setValue?:(v:string)=>void}){return <div className={cn("flex items-center gap-1 rounded-xl bg-background p-1 mb-4",className)}>{React.Children.map(children,(child:any)=>React.isValidElement(child)?React.cloneElement(child,{active:value===child.props.value,onSelect:setValue}):child)}</div>}
export function TabsTrigger({value,children,className,active,onSelect}:{value:string;children:React.ReactNode;className?:string;active?:boolean;onSelect?:(v:string)=>void}){return <button type="button" onClick={()=>onSelect?.(value)} className={cn("rounded-lg px-3 py-2 text-sm font-medium transition",active?"bg-surface text-primary shadow-sm":"text-muted hover:text-ink",className)}>{children}</button>}
export function TabsContent({value,children,className,active}:{value:string;children:React.ReactNode;className?:string;active?:boolean}){return active?<div className={cn("w-full",className)}>{children}</div>:null}
export function Timeline({items}:{items:Array<{date:string|Date;title:string;description?:string;tone?:"default"|"success"|"warning"|"danger"}>}){return <div className="space-y-4">{items.map((item,index)=><div key={`${String(item.date)}-${index}`} className="flex gap-3"><div className={cn("mt-1 h-2.5 w-2.5 shrink-0 rounded-full",item.tone==="success"?"bg-success":item.tone==="danger"?"bg-danger":item.tone==="warning"?"bg-warning":"bg-primary")}/><div className="min-w-0 flex-1 border-b border-border pb-4 last:border-0"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-medium text-ink">{item.title}</p><time className="text-xs text-muted">{String(item.date)}</time></div>{item.description?<p className="mt-1 whitespace-pre-line text-xs leading-6 text-muted">{item.description}</p>:null}</div></div>)}</div>}
export { Search };
